---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: *project_name*
  namespace: *k8s_namespace*
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: *project_name*
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
