apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patchesStrategicMerge:
  - deployment-env.yaml
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: *project_name*
    path: patch-service-account.yaml
