apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cdn-invalidation-processor-svc
  namespace: cdn
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cdn-invalidation-processor-svc
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
