apiVersion: v1
kind: Service
metadata:
  name: cdn-invalidation-processor-svc
  labels:
    app: cdn-invalidation-processor-svc
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: "http"
      protocol: TCP
  selector:
    app: cdn-invalidation-processor-svc
