apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: *project_name*
  namespace: *k8s_namespace*
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: *project_name*
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
