apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./hpa.yaml
  - ./pdb.yaml
commonLabels:
  app.kubernetes.io/name: *project_name*
