apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: *project_name*
  namespace: *k8s_namespace*
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: *project_name*
