apiVersion: v1
kind: Service
metadata:
  name: *project_name*
  labels:
    app: *project_name*
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: "http"
      protocol: TCP
  selector:
    app: *project_name*
